name: "BigMLFlow Tests"

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-01:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]

    steps:
    - name: Install packages
      uses: actions/checkout@v2
    - run: |
        pip install .[test]

    - name: Run Tests
      run: |
        pytest tests
